package coba;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import modul.Global;

/**
 *
 * @author RAMPA
 */
public class FormContoh extends javax.swing.JFrame {

    private Global g = new Global();
    
    private double[][][] TRAINING_DATA = {{
        {9.123456, 3.123456}, {+1}},
    {{9.123456, 5.123456}, {+1}},
    {{5.123456, 5.123456}, {-1}},
    {{8.123456, 6.654321}, {+1}},
    {{4.654321, 4.123456}, {-1}},
    {{2.123456, 4.123456}, {-1}},
    {{9.123456, 7.123456}, {+1}},
    {{4.123456, 4.654321}, {-1}},
    {{8.654321, 2.123456}, {+1}},
    {{2.123456, 2.123456}, {-1}},
    {{3.123456, 3.123456}, {-1}},
    {{8.654321, 4.123456}, {+1}},
    {{7.123456, 6.123456}, {+1}},
    {{4.123456, 7.123456}, {-1}},
    {{6.923456, 4.623456}, {-1}},
    {{8.123456, 5.123456}, {+1}},
    {{3.123456, 4.123456}, {-1}}
    };

    double ZERO = 0.000000009;

    public FormContoh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btnFromCSV = new javax.swing.JButton();
        btnCSVdb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setText("Read From Array");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnFromCSV.setText("Read From CSV");
        btnFromCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromCSVActionPerformed(evt);
            }
        });

        btnCSVdb.setText("Read Read CSV Insert DB");
        btnCSVdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVdbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFromCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCSVdb, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFromCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCSVdb)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

        System.out.println(TRAINING_DATA.length);
        System.out.println("============================");
        double[][] xArray = new double[TRAINING_DATA.length][2];
        double[][] yArray = new double[TRAINING_DATA.length][1];
        for (int i = 0; i < TRAINING_DATA.length; i++) {
            xArray[i][0] = TRAINING_DATA[i][0][0];
            xArray[i][1] = TRAINING_DATA[i][0][1];
            yArray[i][0] = TRAINING_DATA[i][1][0];

            System.out.println(xArray[i][0] + " " + xArray[i][1] + " " + yArray[i][0]);
        }

    }//GEN-LAST:event_btn1ActionPerformed

    private void btnFromCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromCSVActionPerformed
        try {
            int counter = 0;
            Scanner sc = new Scanner(new File("MAXMINX.csv"));
            sc.useDelimiter(",");
            while (sc.hasNext()) {
                if (counter > 3) {
                    counter = 0;
                    System.out.print("");
                } else {
                    System.out.print(sc.next());
                    System.out.print("\t");
                    counter++;
                }
            }
            sc.close();  //closes the scanner  
        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnFromCSVActionPerformed

    private void btnCSVdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVdbActionPerformed
        System.out.println(g.cwdPath());
    }//GEN-LAST:event_btnCSVdbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormContoh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnCSVdb;
    private javax.swing.JButton btnFromCSV;
    // End of variables declaration//GEN-END:variables
}
